---

downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: no
configure_osx: yes

dotfiles_repo: https://github.com/garyjohnson/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/repositories/dotfiles
dotfiles_files:
  - .vim
  - .gitconfig
  - .tmux.conf
  - iterm
  - .macos

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/php

homebrew_cask_apps:
  - docker

homebrew_installed_packages:
  - autoconf
  - git
  - gpg
  - sqlite
  - node
  - nvm
  - readline
  - openssl
  - wget
  - arp-scan
  - tree
  - awk
  - python3


# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 497799835, name: "Xcode (9.2)" }
  - { id: 441258766, name: "Magnet (2.1.0)" }
  - { id: 409183694, name: "Keynote (7.3.1)" }
  - { id: 408981434, name: "iMovie (10.1.8)" }
  - { id: 975937182, name: "Fantastical 2 (2.4.5)" }
  - { id: 1160374471, name: "PiPifier (1.2.4)" }
  - { id: 803453959, name: "Slack (3.0.5)" }
  - { id: 924726344, name: "Deliveries (3.0.7)" }
  - { id: 409201541, name: "Pages (6.3.1)" }
  - { id: 407963104, name: "Pixelmator (3.7)" }
  - { id: 736189492, name: "Notability (2.8.1)" }
  - { id: 409203825, name: "Numbers (4.3.1)" }
  - { id: 506189836, name: "Harvest (2.1.2)" }
mas_email: "gary@gjtt.com"
mas_password: ""

osx_script: "~/.macos --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
